print("this a line of error")
print("this is a second line")

exit(1)